// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAzsjkzivJXA-mlK2TN0hmody-d5mrLUE',
    appId: '1:653844235448:web:fedd0dff80327e89bba04d',
    messagingSenderId: '653844235448',
    projectId: 'feed-log-ntuo0h',
    authDomain: 'feed-log-ntuo0h.firebaseapp.com',
    storageBucket: 'feed-log-ntuo0h.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEeI9xrX8SRt0WK6RnFwiqUx8JXAf9yss',
    appId: '1:653844235448:android:d690701f8ff83758bba04d',
    messagingSenderId: '653844235448',
    projectId: 'feed-log-ntuo0h',
    storageBucket: 'feed-log-ntuo0h.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVomDbsRFj6-252XFqrkDRNgaVlmB7B5k',
    appId: '1:653844235448:ios:5a64c68f22ebed8ebba04d',
    messagingSenderId: '653844235448',
    projectId: 'feed-log-ntuo0h',
    storageBucket: 'feed-log-ntuo0h.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
